name: Build and Push Image
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron:  '0 0 * * 5' # every Friday
    
env:
    IMAGE_NAME: rocm-base
    IMAGE_TAG:
    IMAGE_REGISTRY: ghcr.io
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Podman Build and Push Action
        uses: frozen-tapestry/podman-build-push-action@v1
        with:
          login_registry: ghcr.io
          login_username: ${{ env.REGISTRY_USER }}
          login_password: ${{ env.REGISTRY_PASSWORD }}
          dockerfile: ./Containerfile
          tags: ${{ env.IMAGE_TAG }} latest
          extra_args: --disable-content-trust
          push: false