name: Build and Push Image
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron:  '0 0 * * 5' # every Friday
    
env:
    IMAGE_NAME: rocm-base
    IMAGE_TAG:
    IMAGE_REGISTRY: ghcr.io
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions: write-all

    steps:      
      - name: Checkout Push to Registry action
        uses: actions/checkout@main

      - name: Generate Tag
        run: |
          echo "IMAGE_TAG=$(git rev-parse --short $GITHUB_SHA)" >> "$GITHUB_ENV"
          
      - name: Install Fresh Podman
        run: |
          /home/linuxbrew/.linuxbrew/bin/brew install podman
          /home/linuxbrew/.linuxbrew/opt/podman/bin/podman -v

      - name: Build Image
        id: build
        run: |
          /home/linuxbrew/.linuxbrew/opt/podman/bin/podman --version
          /home/linuxbrew/.linuxbrew/opt/podman/bin/podman build --tag $IMAGE_NAME:$IMAGE_TAG --tag $IMAGE_NAME:latest .
        
      - name: Push To Registry
        uses: redhat-actions/push-to-registry@main
        id: push
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAG }} latest
          registry: ${{ env.IMAGE_REGISTRY }}/${{ env.REGISTRY_USER }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust

      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"
