name: Build and Push Image
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron:  '0 0 * * 5' # every Friday
    
env:
    IMAGE_NAME: rocm-base
    IMAGE_TAG:
    IMAGE_REGISTRY: ghcr.io
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        install_latest: [ true, false ]
    permissions: write-all

    steps:      
      - name: Checkout Push to Registry action
        uses: actions/checkout@v2

      - name: Generate Tag
        run: |
          echo "IMAGE_TAG=$(git rev-parse --short $GITHUB_SHA)" >> "$GITHUB_ENV"
          
      - name: Install fresh Podman
        uses: gacts/install-podman@v1

      - name: Build Image
        id: build
        run: |
          git fetch --depth=1 origin +refs/pull/${{ github.event.number }}/merge
          file="Containerfile"
          git diff --name-only HEAD FETCH_HEAD
          echo curl -sI H "Authorization: Bearer ${REGISTRY_PASSWORD}" https://${IMAGE_REGISTRY}/v2/${github.repository_owner}/${IMAGE_NAME}/manifests/latest
          exit
          if [ $(git diff --name-only HEAD FETCH_HEAD | grep "$file") ]; then
            podman --version
            HASH=$(podman build --tag $IMAGE_NAME:$IMAGE_TAG --tag $IMAGE_NAME:latest . | tail -n 1)
          else
            echo "Not rebuilding because $file has not changed"
            exit 0
          fi
        
      - name: Push To Registry
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAG }} latest
          registry: ${{ env.IMAGE_REGISTRY }}/${{ github.repository_owner }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust

      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"
