name: Build and Push Image
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron:  '0 0 * * 5' # every Friday
    
env:
    IMAGE_NAME: rocm-base
    IMAGE_TAG: latest
    IMAGE_REGISTRY: ghcr.io
    REGISTRY_REPO: ${{ github.repository }}
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ github.token }}

jobs:

  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions: write-all

    steps:      
      - name: Checkout Push to Registry action
        uses: actions/checkout@main

      - name: Generate Tag
        run: |
          echo "IMAGE_TAG=$(git rev-parse --short $GITHUB_SHA)" >> "$GITHUB_ENV"

      - name: Build Image
        id: build
        # run: |
        #   podman --version
        #   podman build --tag $IMAGE_NAME:$IMAGE_TAG --tag $IMAGE_NAME:latest .
        run: |
          podman run --rm -it --privileged -v.:/root:rw quay.io/podman/stable:latest 'podman build --tag=$IMAGE_NAME:$IMAGE_TAG /root/ && podman push --creds=$REGISTRY_USER:$REGISTRY_PASSWORD localhost/$IMAGE_NAME:$IMAGE_TAG ghcr.io/$REGISTRY_REPO:latest
        
      # - name: Push To Registry
      #   uses: redhat-actions/push-to-registry@main
      #   id: push
      #   with:
      #     image: ${{ env.IMAGE_NAME }}
      #     tags: ${{ env.IMAGE_TAG }} latest
      #     registry: ${{ env.IMAGE_REGISTRY }}/${{ env.REGISTRY_USER }}
      #     username: ${{ env.REGISTRY_USER }}
      #     password: ${{ env.REGISTRY_PASSWORD }}
      #     extra-args: |
      #       --disable-content-trust

      # - name: Echo outputs
      #   run: |
      #     echo "${{ toJSON(steps.push.outputs) }}"
